version: '3.9'

services:
  backend:
    build: .
    container_name: ainhotel-be
    ports:
      - "8585:8585"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-35bd5266-votannamquoc-130504.h.aivencloud.com:22125/a_in_hotel
      SPRING_DATASOURCE_USERNAME: avnadmin
      SPRING_DATASOURCE_PASSWORD: AVNS_O-jK8HGG8RAfgfyxA5s
      SERVER_PORT: 8585
      LOGGING_FILE_NAME: /var/log/ainhotel/app.log
    volumes:
      - /var/log/ainhotel:/var/log/ainhotel
